FROM centos:7

WORKDIR /var/www/html

RUN yum update -y && \
    yum install httpd -y && \
    yum clean all

ADD vhost.conf /etc/httpd/conf.d

COPY httpd.conf /etc/httpd/conf/httpd.conf

CMD [ "/usr/sbin/httpd", "-DFOREGROUND" ]
